// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQ5E5r6RrQY-0NvI2GcCJbVYsQCA60Rt0',
    appId: '1:819702799600:web:ac109c79728202964ef635',
    messagingSenderId: '819702799600',
    projectId: 'test-assignment-67647',
    authDomain: 'test-assignment-67647.firebaseapp.com',
    storageBucket: 'test-assignment-67647.firebasestorage.app',
    measurementId: 'G-984F0CDZSS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCe90EpcVBZXk8hlV-Uy2DSDc0pzWEqcDo',
    appId: '1:819702799600:android:2329c81cbd34f9264ef635',
    messagingSenderId: '819702799600',
    projectId: 'test-assignment-67647',
    storageBucket: 'test-assignment-67647.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_WYjsVS3_u2P9tBiCV7AVVVqy8gBLOY4',
    appId: '1:819702799600:ios:03788384f93a772b4ef635',
    messagingSenderId: '819702799600',
    projectId: 'test-assignment-67647',
    storageBucket: 'test-assignment-67647.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_WYjsVS3_u2P9tBiCV7AVVVqy8gBLOY4',
    appId: '1:819702799600:ios:03788384f93a772b4ef635',
    messagingSenderId: '819702799600',
    projectId: 'test-assignment-67647',
    storageBucket: 'test-assignment-67647.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQ5E5r6RrQY-0NvI2GcCJbVYsQCA60Rt0',
    appId: '1:819702799600:web:dd4ad9a6019cecff4ef635',
    messagingSenderId: '819702799600',
    projectId: 'test-assignment-67647',
    authDomain: 'test-assignment-67647.firebaseapp.com',
    storageBucket: 'test-assignment-67647.firebasestorage.app',
    measurementId: 'G-HKR4M3DMVC',
  );
}
